---
title: "Proposal"
author: "Michelle Kelly"
date: "July 16, 2018"
output: pdf_document
---

```{r setup}
# streamPULSE pipeline tools
#library(devtools)
#install_github('streampulse/StreamPULSE', dependencies=TRUE)

# Latest version of streamMetabolizer
#install.packages("streamMetabolizer", dependencies = TRUE, 
#                 repos = c("https://owi.usgs.gov/R", "https://cran.rstudio.com"))

library(lubridate)
#library(dataRetrieval)
library(StreamPULSE)
library(streamMetabolizer)
library(imputeTS)
library(ggplot2)
```

# Introduction  
# Methods  
- describe USGS data and how you collected it
- description of why certain sites were chosen  
- description of methods used to model metabolism
# Results  
- present results of modeling from one site as a preliminary result
# Discussion  
- connect the results back to metabolism regime work done by bernhardt et al 2018, etc
- describe plans for final project

```{r data.import, cache = TRUE}
# for this proposal, pull one USGS site
# full project will do comparison between sites of different conditions: tropical rivers, artic rivers, heavy agricultural rivers, arid rivers

source("dataLoad.R")

# large, aseasonal, little canopy cover: loading CA sacramento data
filepath_CA <- "./data_files/CA_SacramentoR.csv"
lat_CA <- "38.257778"
long_CA <- "-121.517222"
tz_CA <- "America/Los_Angeles"
CA_SacramentoR <- dataLoad(filepath = filepath_CA, lat = lat_CA, long = long_CA, tz = tz_CA)

# small, seasonal, and forested: loading CT data
filepath_CT <- "./data_files/CT_NorthBranchParkR.csv"
lat_CT <- "41.784439"
long_CT <- "-72.708056"
tz_CT <- "America/New_York"
CT_NorthBranch <- dataLoad(filepath = filepath_CT, lat = lat_CT, long = long_CT, tz = tz_CT)

# large, seasonal, agriculturally dominated: Mississippi R at Clinton IA
# gage # 05420500
filepath_IA <- "./data_files/IA_MississippiR.csv"
lat_IA <- "41.780556"
long_IA <- "-90.251944"
tz_IA <- "America/Chicago"
IA_MississipiR <- dataLoad(filepath = filepath_IA, lat = lat_IA, long = long_IA, tz = tz_IA)

# check that data is correct classes with tests.Rmd
str(IA_MississipiR)
```

```{r dataPrep}
# add in data prep function: limit error by re-formatting and interpolating points in a seperate step
```


```{r modeling, cache = TRUE}
source("metabolismModeling.R")
metab_kansasR <- metabolismModeling(kansasR)

metab_WI <- metabolismModeling(WI_Menominee)
```

```{r plotting}
# have a very short function that plots
source("metabolismPlot.R")
metabolismPlot(metab_kansasR)

metabolismPlot(metab_WI)
```